import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { CalendarRange, UsersRound } from 'lucide-react';

function todayForYear(year) { const now = new Date(); return Number(year) === now.getFullYear() ? now.toISOString().slice(0,10) : `${year}-01-15`; }

export default function VacationDailyCoverage({ apiBase, token, year, refreshKey = 0 }) {
    const [date, setDate] = useState(() => todayForYear(year)); const [data, setData] = useState(null); const [error, setError] = useState('');
    useEffect(() => { setDate(todayForYear(year)); }, [year]);
    const load = useCallback(async () => { if (!token || !date) return; try { const response=await fetch(`${apiBase}/api/vacaciones/coverage/day?date=${date}`,{headers:{Authorization:`Bearer ${token}`}}); const body=await response.json(); if(!response.ok) throw new Error(body?.error||'No se pudo calcular la cobertura.'); setData(body); setError(''); } catch(err){setError(err.message);} },[apiBase,token,date,refreshKey]);
    useEffect(()=>{load();},[load]);
    const away=useMemo(()=>data?.approved||[],[data]);
    return <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="flex items-center gap-2 text-lg font-semibold text-slate-900"><CalendarRange size={18}/> Cobertura del día</h2><p className="mt-1 text-sm text-slate-500">Selecciona una fecha para ver quién falta y qué cobertura queda por equipo.</p></div><input type="date" min={`${year}-01-01`} max={`${year}-12-31`} value={date} onChange={(e)=>setDate(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2 text-sm"/></div>{data && <><div className="mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-semibold uppercase text-slate-500">De vacaciones aprobadas</p>{away.length===0?<p className="mt-2 text-sm text-slate-500">Nadie de vacaciones ese día.</p>:<ul className="mt-2 space-y-1 text-sm text-slate-700">{away.map((p)=><li key={p.empleado_id}>{p.empleado_nombre} <span className="text-slate-400">· {p.departamento}</span></li>)}</ul>}</div><div className="rounded-xl bg-amber-50 p-4"><p className="text-xs font-semibold uppercase text-amber-700">Pendientes que podrían afectar</p>{(data.pending||[]).length===0?<p className="mt-2 text-sm text-amber-700/70">Sin solicitudes pendientes ese día.</p>:<ul className="mt-2 space-y-1 text-sm text-amber-800">{data.pending.map((p)=><li key={p.empleado_id}>{p.empleado_nombre} · {p.departamento}</li>)}</ul>}</div></div><div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr><th className="px-3 py-2">Departamento</th><th className="px-3 py-2">Plantilla</th><th className="px-3 py-2">Aprobadas</th><th className="px-3 py-2">Pendientes</th><th className="px-3 py-2">Disponibles</th></tr></thead><tbody>{(data.departamentos||[]).map((row)=><tr key={row.nombre} className="border-t border-slate-100"><td className="px-3 py-3 font-medium">{row.nombre}</td><td className="px-3 py-3">{row.total}</td><td className="px-3 py-3">{row.aprobadas}</td><td className="px-3 py-3">{row.pendientes}</td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${row.disponibles<=1?'bg-rose-50 text-rose-700':row.disponibles<=2?'bg-amber-50 text-amber-700':'bg-emerald-50 text-emerald-700'}`}>{row.disponibles}</span></td></tr>)}</tbody></table></div></>}{error&&<p className="mt-3 text-sm text-rose-700">{error}</p>}</section>;
}
